version: '3.9'

services:
  postgres:
    container_name: postgres-nuxt-template
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - './infrastructure/postgres/data:/var/lib/postgresql/data'

  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - './infrastructure/s3/data:/data'

  minio-client:
    container_name: minio-client
    image: minio/mc
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        mc mb --ignore-existing local/${MINIO_BUCKET}
        mc anonymous set download local/${MINIO_BUCKET}
    depends_on:
      - minio

  redis:
    container_name: redis-nuxt-template
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
